from io import BytesIO
from datetime import date

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer


def generate_cancellation_letter_pdf(contract, user_email: str = None) -> BytesIO:
    buffer = BytesIO()

    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        leftMargin=60,
        rightMargin=60,
        topMargin=50,
        bottomMargin=50,
        title="Cancellation Letter",
    )

    styles = getSampleStyleSheet()

    normal = styles["Normal"]

    small = ParagraphStyle(
        "small",
        parent=normal,
        fontSize=8,
        textColor=colors.grey,
        alignment=1,
    )

    elements = []

    # =====================================================
    # HEADER BLOCK (Sender - currently minimal)
    # =====================================================

    sender_block = """
    John Doe<br/>
    Main Street 15<br/>
    10115 Berlin
    """

    elements.append(Paragraph(sender_block, normal))
    elements.append(Spacer(1, 20))

    # =====================================================
    # RECIPIENT (placeholder SaaS-safe)
    # =====================================================

    recipient_block = f"""
    {contract.company}<br/>
    Customer Service<br/>
    [Company Address Missing]
    """

    elements.append(Paragraph(recipient_block, normal))
    elements.append(Spacer(1, 20))

    # =====================================================
    # DATE
    # =====================================================

    today = date.today().strftime("%d %B %Y")
    elements.append(Paragraph(today, normal))
    elements.append(Spacer(1, 20))

    # =====================================================
    # SUBJECT
    # =====================================================

    subject = f"""
    <b>Subject:</b><br/>
    Termination of {contract.contract_type} Contract
    """

    elements.append(Paragraph(subject, normal))
    elements.append(Spacer(1, 20))

    # =====================================================
    # BODY
    # =====================================================

    body = f"""
    Dear Sir or Madam,<br/><br/>

    I hereby terminate my {contract.contract_type} contract with {contract.company}
    at the earliest possible date.<br/><br/>

    <b>Contract Details:</b><br/>
    Monthly Price: €{contract.monthly_price}<br/>
    End Date: {contract.end_date.strftime("%d.%m.%Y")}<br/>
    Cancellation Deadline: {contract.cancellation_deadline.strftime("%d.%m.%Y")}<br/><br/>

    Please confirm my cancellation in writing.<br/><br/>

    Kind regards,<br/><br/><br/>

    John Doe<br/>
    _____________________<br/>
    Signature
    """

    elements.append(Paragraph(body, normal))
    elements.append(Spacer(1, 30))

    # =====================================================
    # FOOTER
    # =====================================================

    footer = """
    ------------------------------------------------<br/>
    Generated by Bureaucracy Manager
    """

    elements.append(Paragraph(footer, small))

    doc.build(elements)
    buffer.seek(0)
    return buffer