from io import BytesIO
from datetime import date

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer

from app.backend.models.contract import Contract
from app.backend.models.user import User


def generate_cancellation_letter_pdf(contract: Contract, user: User) -> BytesIO:
    buffer = BytesIO()
    
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        leftMargin=60,
        rightMargin=60,
        topMargin=50,
        bottomMargin=50,
        title="Cancellation Letter",
    )

    styles = getSampleStyleSheet()

    normal = styles["Normal"]

    small = ParagraphStyle(
        "small",
        parent=normal,
        fontSize=8,
        textColor=colors.grey,
        alignment=1,
    )

    elements = []
    

    sender_block = f"""
    {user.full_name}<br/>
    {user.address}<br/>
    {user.postal_code} {user.city}
    """

    elements.append(Paragraph(sender_block, normal))
    elements.append(Spacer(1, 20))


    recipient_block = f"""
    {contract.company}<br/>
    Customer Service<br/>
    {contract.company_address}<br/>
    """

    elements.append(Paragraph(recipient_block, normal))
    elements.append(Spacer(1, 20))


    today = date.today().strftime("%d %B %Y")
    elements.append(Paragraph(today, normal))
    elements.append(Spacer(1, 20))


    subject = f"""
    <b>Subject:</b><br/>
    Termination of {contract.contract_type} Contract
    """

    elements.append(Paragraph(subject, normal))
    elements.append(Spacer(1, 20))


    body = f"""
    Dear Sir or Madam,<br/><br/>

    I hereby terminate my {contract.contract_type} contract with {contract.company}
    at the earliest possible date.<br/><br/>

    <b>Contract Details:</b><br/>
    Monthly Price: €{contract.monthly_price}<br/>
    End Date: {contract.end_date.strftime("%d.%m.%Y")}<br/>
    Cancellation Deadline: {contract.cancellation_deadline.strftime("%d.%m.%Y")}<br/><br/>

    Please confirm my cancellation in writing.<br/><br/>

    Kind regards,<br/><br/><br/>

    {user.full_name}<br/>
    _____________________<br/>
    Signature
    """

    elements.append(Paragraph(body, normal))
    elements.append(Spacer(1, 30))

    footer = """
    ------------------------------------------------<br/>
    Generated by Bureaucracy Manager
    """

    elements.append(Paragraph(footer, small))

    doc.build(elements)
    buffer.seek(0)
    return buffer