# FROM python:3.12-slim

# WORKDIR /app

# COPY requirements.txt .

# RUN python -m pip install --upgrade pip
# RUN python -m pip install -r requirements.txt

# COPY . .

# ENV PYTHONPATH=/app
# ENV PYTHONUNBUFFERED=1
# ENV PIP_NO_CACHE_DIR=1
# ENV PIP_ROOT_USER_ACTION=ignore

# CMD ["python", "-m", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]

FROM python:3.12-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    build-essential \
    gcc \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

ENV PYTHONUNBUFFERED=1
ENV PYTHONPATH=/app

CMD ["uvicorn", "app.backend.main:app", "--host", "0.0.0.0", "--port", "8000"]