"""update models

Revision ID: 5c2197ceffc6
Revises: 45a3e88b7015
Create Date: 2026-06-26 13:56:02.819349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c2197ceffc6'
down_revision: Union[str, Sequence[str], None] = '45a3e88b7015'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('company_address', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contracts', 'company_address')
    # ### end Alembic commands ###
