"""add price

Revision ID: dccec1026259
Revises: f5447b3799db
Create Date: 2026-06-06 12:03:22.282820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dccec1026259'
down_revision: Union[str, Sequence[str], None] = 'f5447b3799db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('monthly_price', sa.Numeric(precision=10, scale=2), nullable=False))
    op.create_index(op.f('ix_contracts_cancellation_deadline'), 'contracts', ['cancellation_deadline'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contracts_cancellation_deadline'), table_name='contracts')
    op.drop_column('contracts', 'monthly_price')
    # ### end Alembic commands ###
